package com.studyhub.study;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    STUDY_FILE_UPLOADED,
    POST_CREATED,
    COMMENT_CREATED,
    ATTENDANCE_CHANGED
}
